### ISSUE TITLE
relation to flipper zero

### ISSUE THREAD

**Issue by vaughnmonkey** [flipper-io/flipper#159]
Is this thing somehow related to the [Flipper Zero](https://flipperzero.one/) pintesting tool? Cause if not you might want to consider a name change before they come after you for copywrite infringement. Atleast since you do sell your boards under the name.

**Comment by georgemorgan** [comment]
This project has existed since 2012, much longer than Flipper Zero has. They actually did quite the opposite of coming after us for copyright infringement, offering to acquire the assets for the project but the deal did not work out. :) There are many projects with duplicated names though, so I (and they) are not concerned about it.
